remote_theme: siddhantgoel/clean-jekyll-theme
title: 'Stastic for Jekyll '
name: Test name
description: Stastic test
baseurl: /feckless_stick_figures
lang: en
github_username: johndoe
social:
  name: John Doe
  links:
    - 'https://twitter.com/johndoe'
    - 'https://github.com/johndoe'
